#!/usr/bin/env python3
"""
MonitaQC Startup Script
Auto-detects OS and configures docker-compose accordingly.
  - Linux (production): DATA_ROOT=/mnt/SSD-RESERVE, PRIVILEGED=true
  - Windows/macOS (dev): DATA_ROOT=. (project dir), PRIVILEGED=false
"""
import os
import sys
import platform
import subprocess

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
ENV_FILE = os.path.join(PROJECT_DIR, ".env")


def detect_and_write_env():
    system = platform.system()

    if system == "Linux":
        # Production: use external SSD mount
        data_root = "/mnt/SSD-RESERVE"
        privileged = "true"
        mode = "PRODUCTION (Linux)"
    else:
        # Dev: use local project directory
        data_root = "."
        privileged = "false"
        mode = f"DEVELOPMENT ({system})"

    # Read existing .env to preserve user-defined vars
    existing = {}
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, val = line.split("=", 1)
                    existing[key.strip()] = val.strip()

    # Only set if not already defined by user
    if "DATA_ROOT" not in existing:
        existing["DATA_ROOT"] = data_root
    if "PRIVILEGED" not in existing:
        existing["PRIVILEGED"] = privileged

    with open(ENV_FILE, "w") as f:
        f.write(f"# Auto-generated by start.py - detected: {mode}\n")
        f.write(f"# Override these values manually if needed\n")
        for key, val in existing.items():
            f.write(f"{key}={val}\n")

    print(f"[MonitaQC] Mode: {mode}")
    print(f"[MonitaQC] DATA_ROOT={existing['DATA_ROOT']}")
    print(f"[MonitaQC] PRIVILEGED={existing['PRIVILEGED']}")
    print(f"[MonitaQC] .env written to {ENV_FILE}")

    # Create local volume dirs if using dev mode
    if existing["DATA_ROOT"] == ".":
        for d in ["volumes/redis", "volumes/timescaledb", "volumes/grafana",
                   "volumes/pigallery2_config", "volumes/pigallery2_db", "raw_images"]:
            path = os.path.join(PROJECT_DIR, d)
            os.makedirs(path, exist_ok=True)
        print("[MonitaQC] Local volume directories created")


def main():
    detect_and_write_env()

    # Pass any extra args to docker compose (e.g. "start.py up -d", "start.py down")
    compose_args = sys.argv[1:] if len(sys.argv) > 1 else ["up", "-d"]

    cmd = ["docker", "compose", "-f", os.path.join(PROJECT_DIR, "docker-compose.yml")] + compose_args
    print(f"[MonitaQC] Running: {' '.join(cmd)}")
    sys.exit(subprocess.call(cmd, cwd=PROJECT_DIR))


if __name__ == "__main__":
    main()
